spring:
  application:
    name: eureka-client-1
eureka:
  client:
    serviceUrl:
      defaultZone:
        - http://localhost:1111/eureka/
        - http://localhost:1112/eureka/
  instance:
    home-page-url: http://localhost:8080
    health-check-url: http://localhost:8080