server:
  port: 9000
debug: false
management:
  security:
    enabled: false
spring:
  application:
    name: ribbon-consumer
  zipkin:
    base-url: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5
