server:
  port: 9000
debug: true
management:
  security:
    enabled: false
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
EUREKA-CLIENT-1:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    OkToRetryOnAllOperations: false
    MaxAutoRetries: 1
    MaxAutoRetriesNextSerer: 2