spring:
  application:
    name: eureka-server-2
server:
  port: 1112
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/