spring:
  application:
    name: eureka-server-1
server:
  port: 1111
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka/