spring:
  application:
    name: eureka-server
server:
  port: 1111
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/