spring:
  application:
    name: eureka-server
server:
  port: 1111
management:
  security:
    enabled: false
eureka:
  server:
    eviction-interval-timer-in-ms: 60000
    renewalPercentThreshold: 0.49
#    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/